### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by kubeworkz** [InfyOmLabs/laravel-ui-adminlte#14]
Hi: When I run: `npm run dev` I get the following error. I'm running latest Laravel 8.61.0 and PHP 7.4.23 on Ubuntu 18.04 

```
....
✖ Mix
  Compiled with some errors in 2.65s

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
5 │ @import '~admin-lte/build/scss/AdminLTE';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  resources/sass/app.scss 5:9  root stylesheet
    at processResult (/home/osboxes/erp/kubeworkz/node_modules/webpack/lib/NormalModule.js:721:19)
    at /home/osboxes/erp/kubeworkz/node_modules/webpack/lib/NormalModule.js:827:5
    at /home/osboxes/erp/kubeworkz/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/osboxes/erp/kubeworkz/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/home/osboxes/erp/kubeworkz/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /home/osboxes/erp/kubeworkz/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/home/osboxes/erp/kubeworkz/node_modules/sass/sass.dart.js:95949:16)
    at _render_closure1.call$2 (/home/osboxes/erp/kubeworkz/node_modules/sass/sass.dart.js:83931:12)
    at _RootZone.runBinary$3$3 (/home/osboxes/erp/kubeworkz/node_modules/sass/sass.dart.js:28042:18)
    at _FutureListener.handleError$1 (/home/osboxes/erp/kubeworkz/node_modules/sass/sass.dart.js:26572:21)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 2 errors
....
```

Cheers, Dave

**UPDATE:**

Changed the case of: @import '~admin-lte/build/scss/`AdminLTE`'; to @import '~admin-lte/build/scss/`adminlte`'; in resources/saas/app.scss  Seems to be OK now.

**Comment by BrixSat** [comment]
thans

**Comment by ShaileshInfyom** [comment]
this issue has been fixed in commit https://github.com/InfyOmLabs/laravel-ui-adminlte/commit/03c0c31d76a2e4dd6351cb5a57869d52c3eb8f22

**Comment by EliterDaneo** [comment]
how to impor other css file?
