### ISSUE TITLE
SassError: Top-level selectors may not contain the parent selector "&".

### ISSUE THREAD

**Issue by Roshantwanabasu** [InfyOmLabs/laravel-ui-adminlte#20]
Trying to implement adminlte 3 ui into laravel 8
While running npm run dev, i run into this issue, didnt seem to get anywhere from here 
```
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Top-level selectors may not contain the parent selector "&".
  ╷
7 │   &.bg-#{$name} {
  │   ^^^^^^^^^^^^^^
  ╵
  node_modules/admin-lte/build/scss/mixins/_backgrounds.scss 7:3   background-variant()
  node_modules/admin-lte/build/scss/_colors.scss 7:3               @import
  node_modules/admin-lte/build/scss/parts/_miscellaneous.scss 9:9  @import
  node_modules/admin-lte/build/scss/adminlte.scss 25:9             @import
  resources/sass/app.scss 5:9                                      root stylesheet
    at processResult (/home/roshan/Desktop/project/adminlte-app1/node_modules/webpack/lib/NormalModule.js:758:19)
    at /home/roshan/Desktop/project/adminlte-app1/node_modules/webpack/lib/NormalModule.js:860:5
    at /home/roshan/Desktop/project/adminlte-app1/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /home/roshan/Desktop/project/adminlte-app1/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/home/roshan/Desktop/project/adminlte-app1/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /home/roshan/Desktop/project/adminlte-app1/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/home/roshan/Desktop/project/adminlte-app1/node_modules/sass/sass.dart.js:99696:16)
    at render_closure1.call$2 (/home/roshan/Desktop/project/adminlte-app1/node_modules/sass/sass.dart.js:85096:12)
    at _RootZone.runBinary$3$3 (/home/roshan/Desktop/project/adminlte-app1/node_modules/sass/sass.dart.js:29643:18)
    at _FutureListener.handleError$1 (/home/roshan/Desktop/project/adminlte-app1/node_modules/sass/sass.dart.js:28163:21)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 2 errors
```

**Comment by mitulgolakiya** [comment]
This is a know issue in adminlte. https://github.com/ColorlibHQ/AdminLTE/issues/4586
